export const modelsData = {
	airing_start: String,
	continuing: Boolean,
	episodes: Number,
	genres: Array,
	image_url: String,
	kids: Boolean,
	licensors: Array,
	mal_id: Number,
	members: Number,
	producers: Array,
	r18: Boolean,
	score: Number,
	source: String,
	synopsis: String,
	title: String,
	type: String,
	url: String,
};

export const objeto_anime = {
	request_cached: true,
	request_cache_expiry: 0,
	mal_id: 0,
	url: '',
	image_url: '',
	trailer_url: '',
	title: 'Name',
	title_english: '',
	title_japanese: '',
	title_synonyms: [],
	type: '',
	source: '',
	episodes: 0,
	status: '',
	airing: false,
	aired: {
		from: '2020-10-03T00:00:00+00:00',
		to: '2020-10-03T00:00:00+00:00',
		prop: {
			from: {
				day: 0,
				month: 0,
				year: 0,
			},
			to: {
				day: 0,
				month: 0,
				year: 0,
			},
		},
		string: '',
	},
	duration: '',
	rating: '',
	score: 0,
	scored_by: 0,
	rank: 0,
	popularity: 0,
	members: 0,
	favorites: 0,
	synopsis: '',
	background: null,
	premiered: '',
	broadcast: '',
	related: {
		Adaptation: [],
		'Side story': [],
		Summary: [],
		Prequel: [],
		Sequel: [],
		'Alternative version': [],
	},
	producers: [],
	licensors: [],
	studios: [],
	genres: [],
	opening_themes: [],
	ending_themes: [],
};

export const Object_Anime = {
	anime: [],
	season_year: new Date().getFullYear(),
	season_name: '',
};

export const Object_Manga = {
	request_hash: '',
	request_cached: true,
	request_cache_expiry: 61776,
	mal_id: 0,
	url: '',
	title: '',
	title_english: '',
	title_synonyms: [],
	title_japanese: '',
	status: '',
	image_url: '',
	type: 'Manga',
	volumes: 0,
	chapters: 0,
	publishing: false,
	published: {
		from: '1994-12-05T00:00:00+00:00',
		to: '2001-12-20T00:00:00+00:00',
		prop: {
			from: {
				day: 5,
				month: 12,
				year: 1994,
			},
			to: {
				day: 20,
				month: 12,
				year: 2001,
			},
		},
		string: 'Dec  5, 1994 to Dec  20, 2001',
	},
	rank: 5,
	score: 9.08,
	scored_by: 44737,
	popularity: 41,
	members: 112274,
	favorites: 10834,
	synopsis: '',
	background: '',
	related: {
		'Side story': [],
		Adaptation: [],
		'Alternative version': [],
		'Spin-off': [],
	},
	genres: [],
	authors: [],
	serializations: [],
};
