export const modelsData = {
	airing_start: String,
	continuing: Boolean,
	episodes: Number,
	genres: Array,
	image_url: String,
	kids: Boolean,
	licensors: Array,
	mal_id: Number,
	members: Number,
	producers: Array,
	r18: Boolean,
	score: Number,
	source: String,
	synopsis: String,
	title: String,
	type: String,
	url: String,
};
